### ISSUE TITLE
Add go-chi/cors middleware for preflight CORS checks server-side

### ISSUE THREAD

**Issue by CM-IV** [moneropay/moneropay#3]
I'd love to have this enhancement added to the router, it would allow front end applications to send HTTP requests via the Fetch API.  

Instead of a server side application with its own API that makes the requests to Moneropay in order to get around CORS errors, I could just send HTTP requests via a frontend web app - reducing the overall amount of JavaScript involved.

Would this be a reasonable thing to implement?  Am I missing something here?

**Comment by stnby** [comment]
Hello, you really shouldn't have your front-end communicate directly with MoneroPay server. And we do not want to add unnecessary headers to the responses either. What you could do is add these headers via reverse proxy. Be it Caddy2, Nginx or anything else. You should also use the same reverse proxy to whitelist only certain API endpoints.

**Comment by sausagenoods** [comment]
^ It sounds like a reverse proxy can help in this case. You can also reverse proxy under the same domain, different path to get rid of CORS errors. Closing as not planned.

**Comment by sausagenoods** [comment]
^ It sounds like a reverse proxy can help in this case. You can also reverse proxy under the same domain, different path to get rid of CORS errors. Closing as not planned.
