### ISSUE TITLE
Add SQLite/MySQL support

### ISSUE THREAD

**Issue by recanman** [moneropay/moneropay#4]
Using postgres for this small of an application does not make sense, so maybe adding SQLite and/or MySQL support will make it more accessible to users that do not have enough server resources to run Postgres/don't want to deal with Postgres.

**Comment by sausagenoods** [comment]
Adding MySQL/SQLite support is out of the question since we aren't using [database/sql](https://pkg.go.dev/database/sql), we use [pgx](https://pkg.go.dev/github.com/jackc/pgx/v5). We would need to change the way we connect to database and how we do migrations altogether.

**Comment by stnby** [comment]
I also would love to have SQLite support, will keep this one open and see how difficult it would be to implement this.

**Comment by sausagenoods** [comment]
We're considering to add SQLite support in the next release.

**Comment by sausagenoods** [comment]
Working on this branch https://gitlab.com/moneropay/moneropay/-/merge_requests/10

**Comment by sausagenoods** [comment]
Added SQLite support in v2.4.0, thanks for the help!
