### ISSUE TITLE
As an android library?

### ISSUE THREAD

**Issue by ghost** [moneropay/moneropay#7]
Imagine, monero microtransactions to buy whatever [this person is selling](https://toot.cafe/@pimterry/113684553955714435).

**Comment by sausagenoods** [comment]
This is payment processor which needs to be deployed on a remote server, not embedded into an Android application. The API is quite simple: https://moneropay.eu/guide/workflow.html

That person would need to deploy MoneroPay and integrate it with their backend service. The app then would contact the backend service to get Monero payment information from MoneroPay, manage subscriptions etc.

**Comment by sausagenoods** [comment]
I have enabled the discussions feature just now, feel free to move the conversation over there if needed.
